name: Android - Production

on:
  push:
    branches: [main]

jobs:
  release-android:
    name: Android - Deploy Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"

      - name: Install Fastlane
        run: bundle install

      - name: Install packages
        run: yarn config set network-timeout 100000 & yarn --frozen-lockfile

      - name: Expo Login
        run: yarn expo login --non-interactive -u joaaomanooel

      - name: Distribute Expo
        run: yarn expo publish --non-interactive

      # - name: Create Android Assets Bundle
      #   run: |
      #     yarn react-native bundle \
      #       --platform android \
      #       --dev false \
      #       --entry-file index.js \
      #       --bundle-output android/app/src/main/assets/index.android.bundle \
      #       --assets-dest android/app/src/main/res

      - name: Build
        run: fastlane android build

      - name: Distribute
        run: fastlane android distribute_staging

        env:
          APPCENTER_ANDROID_APP_NAME: ${{ secrets.APPCENTER_ANDROID_APP_NAME_PROD }}
          APPCENTER_OWNER_NAME: ${{ secrets.APPCENTER_OWNER_NAME }}
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          FASTLANE_BUILD_ENVIRONMENT: "production"
