name: iOS - Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.17.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Install pods
        run: cd ios && pod install

      - name: Deploy Production
        run: fastlane ios deploy_production

        env:
          APPCENTER_IOS_APP_NAME_PROD: ${{ secrets.APPCENTER_IOS_APP_NAME_PROD }}
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_BUILD_ENVIRONMENT: production
